### ISSUE TITLE
Add option to add a console script

### ISSUE THREAD

**Issue by eliasdorneles** [audreyr/cookiecutter-pypackage#104]
It would be nice to offer an option to add a console script serving as entry point for the package.

We could add an option `"console_script": "n"` that would add a script with a main function with an entrypoint with the same name as the [project slug](https://github.com/audreyr/cookiecutter-pypackage/blob/f3a99424c0d2945dfabbe111ecf60ccd69d4ae10/cookiecutter.json#L6).

**Comment by cerickson** [comment]
Working on it.

**Comment by cerickson** [comment]
See pull request #179
