### ISSUE TITLE
Add a CONTRIBUTING doc to this repo

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#112]
We need a CONTRIBUTING doc with instructions for potential cookiecutter-pypackage contributors.

**Comment by zaro0508** [comment]
i'm working on it

**Comment by jhonjairoroa87** [comment]
Hi @zaro0508, the following information would be helpful to add in the CONTRIBUTING doc for contributors that use MaxOS.

I got an error trying to install the cryptography dependency on MacOS el capitan, to run the tests:
  pip install cryptography
 
and I solve it installing openssl and running a ln:
  brew install openssl
  cd /usr/local/include
  ln -s ../opt/openssl/include/openssl .

For further information:
https://solitum.net/openssl-os-x-el-capitan-and-brew/

**Comment by audreyr** [comment]
This is done. I will open a separate issue for adding the openssl part to CONTRIBUTING.rst.
