### ISSUE TITLE
Doublequotes in author's name generates invalid setup.py

### ISSUE THREAD

**Issue by elfsternberg** [audreyr/cookiecutter-pypackage#113]
My Github name includes my online nickname in quotes; when used with this package, the result is:

`author="Kenneth M. "Elf" Sternberg"`

... which results in an invalid setup.py.  Escapes of some sort are probably needed here.

**Comment by dot2dotseurat** [comment]
Hi I'm working on this issue. :)

**Comment by eliasdorneles** [comment]
fixed in https://github.com/audreyr/cookiecutter-pypackage/pull/119

Thanks @elfsternberg and @dot2dotseurat !
