### ISSUE TITLE
Add a code style checker

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#140]
Set up a tox environment that checks for code style.

* pycodestyle?
* flake8?

**Comment by eliasdorneles** [comment]
For this I think it will be best to run the style check only in Travis, because tools like flake8 won't work in the template code itself, only on a generated project.

**Comment by eliasdorneles** [comment]
Btw, we should also remove flake8 from the contributing docs, since it won't work for template code.

**Comment by audreyr** [comment]
Talked to @skarbot about this at the sprints. Yes, the style check would be a tox environment in the *generated* project, not the template code. 

Here's an example of what I'm thinking: https://www.dominicrodger.com/2013/07/26/tox-and-travis/

**Comment by audreyr** [comment]
Done in #152.
