### ISSUE TITLE
Add ISCL and Apache 2.0 License

### ISSUE THREAD

**Issue by dot2dotseurat** [audreyr/cookiecutter-pypackage#154]
Should follow format from https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/LICENSE
and and use license information from https://opensource.org/licenses/

**Comment by dot2dotseurat** [comment]
I am working on this.

**Comment by audreyr** [comment]
Done in #155
