### ISSUE TITLE
Create a Troubleshooting document

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#174]
* Create `{{cookiecutter.project_slug}}/docs/troubleshooting.rst`
* Integrate @jschwarzwalder's feedback from #120, #122, #125, #124, #123 into that document. Give each pain point its own heading, and write text that formats it as Problem and Solution.

**Comment by dot2dotseurat** [comment]
I will give this a shot

**Comment by audreyr** [comment]
🔔  @purplediane

**Comment by purplediane** [comment]
Working on it from PDX.
