### ISSUE TITLE
Add Appveyor Windows builds for this repo

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#186]
Here's an example: 
https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml
https://ci.appveyor.com/project/audreyr/cookiecutter/branch/master

**Comment by audreyr** [comment]
While setting this up, I discovered that one of the tests fails on Windows:
https://ci.appveyor.com/project/audreyr/cookiecutter-pypackage/build/job/c97mlsydoq8ceiqp

**Comment by eliasdorneles** [comment]
Hm, nice catch!
Yeah, we're assuming there is `make` command available -- not the case on Windows. :/

**Comment by audreyr** [comment]
Ah, I see. Just filed #208 to track it. Closing this since Appveyor's working now for this repo.
