### ISSUE TITLE
Switch to pyup.io for tracking requirements

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter-pypackage#204]
pyup.io is by Cookiecutter Django core dev @jayfk, it's built off Cookiecutter tech. What's not to love?

Needs to be done for both the template and the generated package.

**Comment by jayfk** [comment]
#205 covers `requirements_dev.txt` and `{{cookiecutter.project_slug}}/requirements_dev.txt`. Is this correct?

**Comment by eliasdorneles** [comment]
@jayfk the `requirements_dev.txt` file at top level contains the development dependencies for the template developers (for running the template tests, etc).

The `{{cookiecutter.project_slug}}/requirements_dev.txt` file (which you might notice that has jinja2 tags) is part of the template, and when rendered, it defines the development dependencies for the generated project.

#205 is only covering the first file.

**Comment by jayfk** [comment]
@eliasdorneles That's because `{{cookiecutter.project_slug}}/requirements_dev.txt` is already up-to-date.

It's being processed by the bot. As soon as there is an update it will be covered, too.

**Comment by eliasdorneles** [comment]
ah, cool, got it! :)

**Comment by audreyr** [comment]
While you're both in here, I should introduce you ⛄ 
@jayfk meet Cookiecutter PyPackage core dev @eliasdorneles. @eliasdorneles meet Cookiecutter Django core dev @jayfk.

Also the core of pyup.io is open-source, which is awesome.

requires.io is now deactivated, so this is complete. Closing.

**Comment by eliasdorneles** [comment]
hi there @jayfk, nice meeting you. :smiley:
