### ISSUE TITLE
Change requires.io badge in generated README to pyup.io

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#207]
- See README.rst for an example of a pyup.io badge
- Open `{{cookiecutter.project_slug}}/README.rst`. Look for its requires.io badge and change it to the pyup.io badge
- Update the root README and the Cookiecutter PyPackage tutorial to mention that this comes with a pyup.io badge set up by default, and that you'll need to log into pyup.io and turn on your repo

/cc @jayfk

**Comment by lukegb** [comment]
This can be closed, I think.
