### ISSUE TITLE
Get Appveyor build to pass on Windows

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#208]
1. Study https://ci.appveyor.com/project/audreyr/cookiecutter-pypackage/branch/master and note that one of the tests is failing.
2. Get the test to pass:
   - Maybe you need to install make on the Appveyor worker by modifying `appveyor.yml`?
   - Maybe there is something else going on?

**Comment by browniebroke** [comment]
I'm willing to help, but it's all green over there, can this be closed? @eliasdorneles
If not, a few more details would be helpful for a beginner...

**Comment by eliasdorneles** [comment]
I think we forgot to close this, there was an issue that was fixed by appveyor team.
Closing now, thanks!
