### ISSUE TITLE
Do no parametrize the BSD license

### ISSUE THREAD

**Issue by pombredanne** [audreyr/cookiecutter-pypackage#227]
### Description
In https://github.com/audreyr/cookiecutter-pypackage/blob/cbcdd19a64aaa0c5bcbcc723c75628f44b13f525/%7B%7Bcookiecutter.project_slug%7D%7D/LICENSE#L27 the project name is added to a BSD license template.

I maintain https://github.com/nexB/scancode-toolkit that does detect licenses and creating multiple variants of the BSD is not a great idea for detection nor for helping downstream users.
Instead I suggest using the working of the SPDX licenses list  and not inject any name in the license templates (disclaimer I am a cofounder of SPDX)
http://spdx.org/licenses/BSD-3-Clause.html

**Comment by eliasdorneles** [comment]
Makes sense, sending a PR

**Comment by pombredanne** [comment]
@eliasdorneles thank you for #228 ... may a quick unit test would be make sense too?

**Comment by eliasdorneles** [comment]
So, we already have tests for generating licenses, I don't think it requires more than what we have (we don't need to test the whole license contents).
I'm merging the PR to move this forward.
Thanks @pombredanne !

**Comment by pombredanne** [comment]
@eliasdorneles Thanks!
