### ISSUE TITLE
Project slug suggestion should replace hyphen (-) for underscore (_)

### ISSUE THREAD

**Issue by matibarriento** [audreyr/cookiecutter-pypackage#250]
- Date you used Cookiecutter PyPackage: 2016-10-26
- Cookiecutter version used, if any: 1.4.0
- Python version, if any: 3.5.2
- Operating System: ArchLinux
### Description

When you create a project, the project_name can contains hyphen, but in the next step, the project_slug can't. The project_slug suggestion is the project_name and you can put the same value, but  then will fail because "The project slug (foo-bar) is not a valid Python module name. Please do not use a - and use _ instead".
So i think the default value should be project_name.replace("-", "_")

**Comment by jakirkham** [comment]
Ran into this today as well. The simple fix proposed seems reasonable IMHO.
