### ISSUE TITLE
Proposed changes to test suite

### ISSUE THREAD

**Issue by mandeep** [audreyr/cookiecutter-pypackage#254]
Hi cookiecutters,

I noticed that the test suite in the project is using the unittest style tests for pytest (setup, teardown, etc.). I think these tests should be changed to use pytest fixtures and other pytest style tests. It also looks like the test function for click's CliRunner is written for both pytest and unittest, I propose just having one function in order to avoid duplication. Another thing I noticed is that the test file ends with if dunder name == dunder main. I propose that this be removed since unittest is discoverable with python -m unittest discover. One last thing, which I think can be debated, the tests directory is in the project slug's root directory. I propose moving this directory inside the package directory. Please let me know what you think and I will be happy to submit a pull request for any of the approved changes.

Proposed changes:

- Convert pytest tests from unittest style to pytest style
- Remove duplication of the cli test function (CliRunner)
- Remove if dunder name == dunder main since unittest is discoverable
- Move tests directory inside package directory

**Comment by eliasdorneles** [comment]
Hm, I'd rather keep the tests directory where it is.
What's your motivation for moving them to inside the package?

The other changes sound okay to me, though I wonder if removing dunder name == dunder main could break `python setup.py test` -- that's something to check.

In any case, the best to way to move forward is to submit a PR and we can discuss it there. ;-)

**Comment by mandeep** [comment]
Hi @eliasdorneles, since the tests are testing the CLI application that is in the package, it makes more sense to me to move the directory inside the package directory. I'll submit a PR and we can go from there. 

Thanks!

**Comment by eliasdorneles** [comment]
Well, [both layouts are common practices](http://doc.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules) and while I understand some people might like it different, I see no point on changing the current one -- which is valid, has been tested, and users are already familiar with it.

**Comment by mandeep** [comment]
Great points, I'll leave it be and focus on the other changes.

**Comment by eliasdorneles** [comment]
Closed by #255

**Comment by egberts** [comment]
This article details the various Python directory layouts:  https://blog.ionelmc.ro/2014/05/25/python-packaging/
