### ISSUE TITLE
sub packages are not included (hence not installed)

### ISSUE THREAD

**Issue by feigaoxyz** [audreyr/cookiecutter-pypackage#257]
* Date you used Cookiecutter PyPackage:
* Cookiecutter version used, if any: 1.4.0
* Python version, if any: 3.5
* Operating System: macOS

### Description

sub packages are not included in the setup.py.

### What I Did

Structure of codes:

```
(test-pypkg) $ tree parent/
parent/
├── __init__.py
├── child
│   └── __init__.py
├── cli.py
└── parent.py
```

Install:

```
(test-pypkg) $ python setup.py install
(test-pypkg) $ pip freeze
click==6.6
parent==0.1.0
...
```

But `parent.child` is not installed since [`setup.py`](https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py#L39-L41) only registered top-level package.

```
(test-pypkg) $ tree $CONDA_HOME/envs/test-pypkg/lib/python3.5/site-packages/parent
/Users/user/.local/opt/miniconda3/envs/test-pypkg/lib/python3.5/site-packages/parent
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-35.pyc
│   ├── cli.cpython-35.pyc
│   └── parent.cpython-35.pyc
├── cli.py
└── parent.py
```

**Comment by pydanny** [comment]
Thanks for the feature request, but this is out of scope for this project.
