### ISSUE TITLE
Pycharm settings generated expect docker?

### ISSUE THREAD

**Issue by HintikkaKimmo** [audreyr/cookiecutter-pypackage#261]
* Date you used Cookiecutter PyPackage: 19.10.2016
* Cookiecutter version used, if any: 1.4.0
* Python version, if any: Python 2.7.12
* Operating System: OSX 10.10.5

### Description

I attempted to build AWS Beanstalk application + RDS Postgres 9.4 without docker while developing on PyCharm. The result is basically working application but all .idea Pycharm settings seems be geared towards developing with Docker. Does this work as expected or should Pycharm settings be generated based on other project options selected? In my environment commands below create Pycharm configuration where all run commands are for docker containers. 

### What I Did

```
cookiecutter https://github.com/pydanny/cookiecutter-django
use_pycharm [n]: y
use_docker [y]: n
Select postgresql_version:2
use_elasticbeanstalk_experimental: Y
```

**Comment by luzfcb** [comment]
@HintikkaKimmo I think the correct repository for this is https://github.com/pydanny/cookiecutter-django

**Comment by HintikkaKimmo** [comment]
Absolutely correct. Had this open for something else.
