### ISSUE TITLE
py.test docs say no __init__.py file in tests folders

### ISSUE THREAD

**Issue by michaelaye** [audreyr/cookiecutter-pypackage#268]
* Date you used Cookiecutter PyPackage:
11/07/2016
* Cookiecutter version used, if any:
1.4.0
* Python version, if any:
3.5
* Operating System:
macOS
### Description
I forked cookiecutter-pycackage and renamed to cookiecutter-pypackage to create something that fits well for conda (e.g. removing tox stuff that still doesn't work with conda).

### What I Did
```
cookiecutter https://github.com/michaelaye/cookiecutter-pypackage-conda.git
```
I see that the `tests` subfolder contains an `__init__.py` file, which isn't recommended, according to the py.test docs [here](http://doc.pytest.org/en/latest/goodpractices.html).
I'm not understanding template-ing well yet, what do I need to do to not create an `__init__.py` file in my fork?
Thanks a lot for the cookiecutter!

**Comment by eliasdorneles** [comment]
Hello, @michaelaye !
If you don't want the `__init__.py` file to be generated by your template, just delete it from the template.

In the case of cookiecutter-pypackage, we made a conscious choice of keeping the `__init__.py` on the tests folder, to make it easy for people that might not run `pip install -e .`.

We could revisit the decision if there is a compelling reason to avoid it, but I'm not aware of any.
