### ISSUE TITLE
Clarify Python version support in Makefile

### ISSUE THREAD

**Issue by dennis-tra** [audreyr/cookiecutter-pypackage#359]
Hey guys,

how well does this project template play with python 3 only projects? I saw in the `Makefile` that there is a hard dependency on using the `python` instead `python3` interpreter.
In the docs it's also stated that I could create a virtual environment. With python 3.6 the recommended way is to use the built in `venv`. If I install all my dependencies in the virtual environment using `venv` with `pip3`, is it still possible to leverage all the preconfiguration offered by this template?

On the other hand I saw that tox is configured to test the package against python 3.x versions.

Thanks,
Dennis

**Comment by pydanny** [comment]
Works great with Python3. In fact, we primarily code this project in Python 3.6 these days.
