### ISSUE TITLE
With virtualenv inside project this runs  ~700 unit tests out of the gate.

### ISSUE THREAD

**Issue by brettswift** [audreyr/cookiecutter-pypackage#367]
* Date you used Cookiecutter PyPackage: 9/15/2017
* Cookiecutter version used, if any: 1.5.1
* Python version, if any: 3.6.2
* Operating System: OSX

### Description

With a local virtualenv (called pyenv for reference on the snippets below)  the unit tests run 

### What I Did

```
pyenv/lib/python3.6/site-packages/wheel/test/test_tool.py:5: in get_keyring
    WheelKeys, keyring = tool.get_keyring()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_keyring():
        try:
            from ..signatures import keys
            import keyring
            assert keyring.get_keyring().priority
        except (ImportError, AssertionError):
>           raise WheelError("Install wheel[signatures] (requires keyring, keyrings.alt, pyxdg) for signatures.")
E           wheel.tool.WheelError: Install wheel[signatures] (requires keyring, keyrings.alt, pyxdg) for signatures.

pyenv/lib/python3.6/site-packages/wheel/tool/__init__.py:34: WheelError
============================================== 8 failed, 619 passed, 31 skipped, 1 error in 8.47 seconds ==============================================
```

I'm pretty new to python, but it seems the most sane to have a virtual environment inside each project to keep things isolated.   It seems like a bad practice to keep these virtual environments outside the project root..  which is what most tutorials seem to suggest.   I guess that is what people are doing here, and why these tests are running inside the virtualenv? 

How do you  make this project work for you ?   I'm assuming you use virtualenv's...  

virtuaenv setup
```
#!/bin/bash
env_name=pyenv
virtualenv -p python3 $env_name
source $env_name/bin/activate
pip install -r requirements_dev.txt
```

Would it make sense to bake in virtualenv workflow into this project?

**Comment by luzfcb** [comment]
try use  virtualenvwrapper and stop suffering :-) 

https://virtualenvwrapper.readthedocs.io/en/latest/

**Comment by brettswift** [comment]
I'll give that a shot, but it seems to just make some of the commands easier to switch environments.  It's still a python environment outside of your project.

You can do the same without the wrapper.  Is that wrapper the standard?    

It'd be nice if the Pipfile and Pipfile.lock support that works well in Ruby, would come soon.

**Comment by brettswift** [comment]
seems to help out a bit.   Now if only the packages would resolve.   lol

**Comment by brettswift** [comment]
ps. thanks :)
