### ISSUE TITLE
path lookups failing

### ISSUE THREAD

**Issue by brettswift** [audreyr/cookiecutter-pypackage#368]
* Date you used Cookiecutter PyPackage: 9/15/2017
* Cookiecutter version used, if any: 1.5.1
* Python version, if any:  3.6.2
* Operating System: OSX

### Description

If this is the most popular module I would expect things to work out of the gate.. is this not the case? 

I created a new project called "experiments" to play around and learn a bit of python.   I thought of using cookiecutter to get a project set up with best practices to learn a bit faster. 

However, I'm unable to even resolve packages.  It seems like I'm doing something fundamentally wrong, or python's path lookup is just a bit obtuse. 

### What I Did

Project structure in `~/src/experiments`: 

* `./experiments/`
   * |__`./cli.py`
   * |__ `./main.py`
* `pyenv/` (virutalenv)

cli.py code: 

```
import click

from experiments.ResourceType import resource_type
from experiments.main import TestClass


@click.command()
def main(args=None):
    """Console script for experiments."""
    test = TestClass()


if __name__ == "__main__":
    main()
```

Error: 
```
python ./experiments/cli.py
Traceback (most recent call last):
  File "./experiments/cli.py", line 8, in <module>
    from experiments.main import TestClass
ModuleNotFoundError: No module named 'experiments.main'

python --version
Python 3.6.2
```

What's going on here?   This seems like a fundamental error for a boilerplate project that has a lot of people on it.   Am I missing some python thing that is not documented?

**Comment by luzfcb** [comment]
with your virtualenv active, install the project on [editable mode](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs)

inside de project folder
```
pip install -e .
```

after:
```
experiments
```

**Comment by brettswift** [comment]
thanks again.    I didn't know about the -e flag.
