### ISSUE TITLE
Clarify or improve version number handling

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#38]
From @mcdonc:
> people try to import __version__ from within setup.py which has hilarious results often
> it makes more sense if you consider what can go bad when you try to import something from a pkg you're installing before you install it

@mcdonc's recommendation to avoid the `setup.py` chicken-before-egg problem:
> using pkg_resources avoids this, and the canonical version number lives in one place, setup.py

I've seen a number of people mistakenly refactor the `setup.py` here to import `__version__`. cookiecutter-pypackage needs to either:
* Comment the current approach more clearly in both `setup.py` and `__init__.py`
* Consider using `pkg_resources` rather than `__version__`

**Comment by eliasdorneles** [comment]
Now that version bumping is configured with bumpversion, this issue can probably be closed.

/me loves the smell of solved issues closing in the morning. =)

**Comment by eliasdorneles** [comment]
Alright, I'm closing this.
