### ISSUE TITLE
Remove Python 2.7 support

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter-pypackage#405]
Like the title says.

**Comment by jamesmyatt** [comment]
It's time to do this. Python 2.7 EOL is less than 6 months away (https://pythonclock.org/). Many projects have already dropped feature releases for Python 2.7 (https://python3statement.org/), including venerable projects like pytest, dateutil, numpy, ipython.

Also Python 3.4 is already EOL and should be removed.
