### ISSUE TITLE
Consider modifying usage of find_packages

### ISSUE THREAD

**Issue by micahjsmith** [audreyr/cookiecutter-pypackage#423]
Currently, [find_packages is used](https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py#L61) as follows:

    packages=find_packages(include=['{{ cookiecutter.project_slug }}']), 

If the user creates a package `foo` and then creates a subpackage `foo.bar` (i.e. `bar` is a directory with an `__init__.py`), then the subpackage needs to be added explicitly to the packages list in `setup.py`.

I think that this can lead to unexpected consequences. For example, suppose the user forgets to add `foo.bar` to the package list. All tests will pass locally if they run `tox` or `pytest` from the project root directory because `foo.bar` is on the system path. All tests will pass on CI because the tests are executed from the project directory again. But if an end-user then pip installs the package, `import foo.bar` will result in an import error because the `bar` package will not have been installed to `site-packages` per `setup.py`. (This just happened to me, and it was impossible to debug until I finally `ls`ed the `site-packages` directory of the environment I installed my own package to.)

I suggest to consider a slightly different paradigm which is used by Pandas [for example](https://github.com/pandas-dev/pandas/blob/master/setup.py#L735).

    packages=find_packages(include=['{{ cookiecutter.project_slug }}', '{{ cookiecutter.project_slug }}.*']), 

The usual downside to this usage would be that a `tests` subpackage of `foo` would be installed, but that is not an issue in this pypackage organization.

Thoughts?

**Comment by bluesurfer** [comment]
I have been bitten by this. The solution should definitely be merged imho

**Comment by micahjsmith** [comment]
@bluesurfer thanks for the bump, just created a PR as well.
