### ISSUE TITLE
Consider replacing bumpversion by bump2version

### ISSUE THREAD

**Issue by luzfcb** [audreyr/cookiecutter-pypackage#437]
[bumpversion [1]](https://github.com/peritus/bumpversion) does not receive any updates since 2015, and the repository has no active maintainer.

[bump2version [2]](https://github.com/c4urself/bump2version)  is a fork, which is apparently being maintained.

[1] https://github.com/peritus/bumpversion

[2] https://github.com/c4urself/bump2version

**Comment by CMeza99** [comment]
the maintainer of bumpversion has stated
>I should probably add a sunsetting notice to the top of the README, saying this is not actively maintained and people should switch to one of the forked versions.
--https://github.com/peritus/bumpversion/issues/169#issuecomment-339023681

**Comment by hugovk** [comment]
Duplicate of https://github.com/audreyr/cookiecutter-pypackage/issues/424.
