### ISSUE TITLE
Use a "src" directory?

### ISSUE THREAD

**Issue by jab** [audreyr/cookiecutter-pypackage#442]
I recently saw the rationale for using a "src" directory described in http://andrewsforge.com/article/python-new-package-landscape/ and was curious what you think.

**Comment by CMeza99** [comment]
this is another good reference https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

**Comment by pydanny** [comment]
Use of `src` or not is 100% personal preference. It doesn't really matter. For example, neither Flask, Zappa, Django, Requests, Responses, Responders, etc use the `src` approach. It's a legacy of another time, nothing more.

Thank you for your consideration, but I'm closing this as a `wontimplement`.

**Comment by CMeza99** [comment]
I agree that it is a personal preference. But to say it "doesn't matter" and "legacy of another time, nothing more", is a curt reply to the question. There is a rational for the src-layout as discussed in several blog articles. Even pytest has a use case where they recommend it, https://docs.pytest.org/en/latest/goodpractices.html. Also, there is a long thread in PyPUG issue [#320](https://github.com/pypa/python-packaging-user-guide/issues/320) on this topic. @jab was asking for the your opinion, I guess he got it.

**Comment by pydanny** [comment]
My apologies if i came across as being curt. There are better ways forme to express my opinion. I'll try to do it better next time.

**Comment by jab** [comment]
@pydanny, hope you're doing well. Just hit this issue again. Re your comment citing Flask as a counterexample, @davidism moved several of the Pallets projects (Flask, Jinja, Click, Werkzeug, etc.) to using a `src` directory a while ago. Not sure if you had time to read any of the links cited above, but they actually provide technical justifications for doing this, rather than it being 100% personal preference or nothing more than a legacy of another time. When I opened this issue, I was genuinely curious if you had any _technical_ counterarguments to the rationale presented above, and I still am, in case you're interested to dig into this a little more. Thanks :)
