### ISSUE TITLE
requirements-dev

### ISSUE THREAD

**Issue by marltu** [audreyr/cookiecutter-pypackage#45]
There are currently no requirements-dev.txt

Consider adding it for packages like flake8, etc.

**Comment by davoclavo** [comment]
:+1:

These are the packages I've spotted that require installation
  * flake8
  * tox
  * coverage
  * shpinx

**Comment by pydanny** [comment]
:+1: I'll see if I can get a PR in tomorrow.

**Comment by curtisforrester** [comment]
There is a requirements_dev.txt now, but no requirements.txt... Is that intentional?

**Comment by audreyr** [comment]
@curtisforrester Yes, it's intentional, see https://github.com/audreyr/cookiecutter-pypackage/pull/61
