### ISSUE TITLE
ENH: setup.py: Read version from __init__.py:__version__ with a regex

### ISSUE THREAD

**Issue by westurner** [audreyr/cookiecutter-pypackage#475]
If we read the version from `__init__.py:__version__` with a regex in setup.py,
we don't need to change the version in setup.py, too:
https://stackoverflow.com/questions/17791481/creating-a-version-attribute-for-python-packages-without-getting-into-troubl/41110107#41110107

**Comment by westurner** [comment]
setuptools_scm may be a good addition *instead*:
https://github.com/pypa/setuptools_scm

>  the blessed package to manage your versions by scm tags

**Comment by PsiACE** [comment]
Great idea, but now bump2version works fine. We should give priority to some basic work, not to help users make choices.
