### ISSUE TITLE
English course image links to spannish website

### ISSUE THREAD

**Issue by mikeWShef** [audreyr/cookiecutter-pypackage#497]
On GitHub the image with the English text ("Creating and distributing python packages") links to the Spanish website. The Spanish text links to the same website

**Comment by hamed2005** [comment]
Should be replaced by https://twoscoopspress.thinkific.com/courses/creating-and-distributing-python-packages

**Comment by PsiACE** [comment]
There appears to be a PR  #452  already, but it has not been merged into the repository.

**Comment by PsiACE** [comment]
It's done. You can check them.
