### ISSUE TITLE
Sphinx renders locally but not when hosted on readthedocs.io

### ISSUE THREAD

**Issue by aidanmelen** [audreyr/cookiecutter-pypackage#526]
* 09/16/2019
* cookiecutter: 1.6.0
* Python: 3.7.4
* Operating System: MacOS

### Description

I am most certainly incorrectly deploying the docs for a python tool that I am writing called [awscli-bastion](https://github.com/aidanmelen/awscli_bastion). When I run ```make docs```, my source code is hosted locally and I can see that all my module functions are auto documented. This is really cool!

### What I Did

```
make docs
# this hosts the docs correctly from my local machine

make clean
make release
```

then I go to https://awscli-bastion.readthedocs.io/en/latest/awscli_bastion.html and make a new build and it fails to auto document the source code. It is weird because it is half working. There is a section for each module, but the functions within the modules are not documented.

I have no idea what I am doing wrong. I bet I am missing a step to package the docs before the release or something like that.

**Comment by PsiACE** [comment]
If you're just rebuilding it, it may take a while. In addition, I might suggest going to the readthedocs.org  and clicking the build button.

Could you provide the readthedocs build log?

**Comment by aidan-melen** [comment]
Here are the logs from the latest build.

https://readthedocs.org/api/v2/build/9667746.txt

Not really sure why these are failing.
```
WARNING: autodoc: failed to import module 'cache' from module 'awscli_bastion'; the following exception was raised:
No module named 'dateutil'
WARNING: autodoc: failed to import module 'cli' from module 'awscli_bastion'; the following exception was raised:
No module named 'botocore'
WARNING: autodoc: failed to import module 'credentials' from module 'awscli_bastion'; the following exception was raised:
No module named 'botocore'
WARNING: autodoc: failed to import module 'minimal' from module 'awscli_bastion'; the following exception was raised:
No module named 'boto3'
WARNING: autodoc: failed to import module 'sts' from module 'awscli_bastion'; the following exception was raised:
No module named 'botocore'
```

Should I add ```import dateutil botocore boto3``` to the *docs/conf.py* file?

**Comment by PsiACE** [comment]
Sorry, I didn't deal with this issue in time, but your page now seems to be completely normal.

**Comment by aidan-melen** [comment]
okay, I was able to get the dependencies to install by creating a docs/requirements.txt file containing the following:

```
Click>=6.0
boto3>=1.5.0
awscli>=1.13.0
humanize>=0.5.1
docutils>=0.15.2
```

It would be more ideal to reference the setup.py for the requirements, that way I do not have to define them twice.

**Comment by aidan-melen** [comment]
if .readthedocs.yml doesn't support setup.py for installing requirements, we can close this issue. thanks again for helping out.

**Comment by aidan-melen** [comment]
You can. Put -e .[docs] in your requirements.txt, assuming you have added a docs_extra. This is what we do for Pyramid.

**Comment by aidan-melen** [comment]
sorry we can close this issue. probably shouldn't have created it in the first place

**Comment by PsiACE** [comment]
Would you like to add a FAQ document for us?
