### ISSUE TITLE
Include Python 3.8 support

### ISSUE THREAD

**Issue by PsiACE** [audreyr/cookiecutter-pypackage#531]
- In tox.ini
- In .travis.yml
- In setup.py
- Throughout the docs wherever other versions are mentioned
- Anywhere else that should be included

**Comment by PsiACE** [comment]
[appveyor/ci #3142](https://github.com/appveyor/ci/issues/3142)

**Comment by hugovk** [comment]
🚀 Python 3.8 is now available on AppVeyor:

* https://github.com/appveyor/ci/issues/3142#issuecomment-552049896

**Comment by ChadBailey** [comment]
Found 2 other places 3.8 needed to be added so included this as a part of PR https://github.com/audreyr/cookiecutter-pypackage/pull/543
