### ISSUE TITLE
new project fails because of unexpected argument 'keep_trailing_newline'

### ISSUE THREAD

**Issue by arundurvasula** [audreyr/cookiecutter-pypackage#54]
Hi,

I'm trying to start a new project with cookiecutter-pypackage. I ran 

    cookiecutter cookiecutter-pypackage/

after cloning this repository with `git clone https://github.com/audreyr/cookiecutter-pypackage.git` and editing the json file. I get this as an error message:

    Traceback (most recent call last):
      File "/Users/arundurvasula/anaconda/bin/cookiecutter", line 9, in <module>
        load_entry_point('cookiecutter==0.9.1', 'console_scripts', 'cookiecutter')()
      File "/Users/arundurvasula/anaconda/lib/python2.7/site-packages/cookiecutter/main.py", line 169, in main
        cookiecutter(args.input_dir, args.checkout, args.no_input)
      File "/Users/arundurvasula/anaconda/lib/python2.7/site-packages/cookiecutter/main.py", line 105, in cookiecutter
        context=context
      File "/Users/arundurvasula/anaconda/lib/python2.7/site-packages/cookiecutter/generate.py", line 181, in generate_files
        env = Environment(keep_trailing_newline=True)
    TypeError: __init__() got an unexpected keyword argument 'keep_trailing_newline'

I also tried `cookiecutter https://github.com/audreyr/cookiecutter-pypackage` but that failed with the same error. 

I'm using the anaconda distribution of python. Any ideas about what's wrong?

Thanks a lot! I'm looking forward to using this.

**Comment by pydanny** [comment]
Which python are you using? Python 2.7 or Python 3.x?

**Comment by arundurvasula** [comment]
Python 2.7

**Comment by pydanny** [comment]
Okay. I found out earlier this week that the conda packages for cookiecutter were only compiled for Python 3. I haven't had the time to add the ones for Python 2. For that you have my apologies.

**Comment by arundurvasula** [comment]
Oh cool, no worries and no rush! Thanks for following up!

**Comment by arundurvasula** [comment]
I updated my packages with conda update and everything seems to be working now. Thanks!
