### ISSUE TITLE
[Question] Cookiecutter template for CircleC

### ISSUE THREAD

**Issue by neomatrix369** [audreyr/cookiecutter-pypackage#548]
### Description

I have been advised to ask my question that I had asked in the https://github.com/cookiecutter/cookiecutter repo to be asked here instead. So below is the repeat of it:

Really like the tool and the idea behind it, great to see it has taken off amazingly with so much usage all across GitHub and elsewhere.

Wish to generate a project using a python template that generates config for CircleCI instead of the default TravisCI.

I have raised an issue on StackOverflow explaining with details:
https://stackoverflow.com/questions/58312858/is-there-a-cookiecutter-fork-that-generates-a-project-template-for-circleci-ins

Would really appreciate any hints or tips on it - I heard there is some template of this sort out there.

### What I Did

Nothing so far, still exploring my options

**Comment by caleb15** [comment]
https://github.com/nolte/cookiecutter-circleci

**Comment by neomatrix369** [comment]
Thanks @caleb15 someone pointed this out to me on SO
