### ISSUE TITLE
[Question] git tracking of files

### ISSUE THREAD

**Issue by arturomoncadatorres** [audreyr/cookiecutter-pypackage#593]
Hi! This is my first time creating a package. I am following the instructions in the [tutorial](https://cookiecutter-pypackage.readthedocs.io/en/latest/tutorial.html). By the way, thank you for writing one, it is incredibly useful.

I have a question. In [Step 3](https://cookiecutter-pypackage.readthedocs.io/en/latest/tutorial.html#step-3-create-a-github-repo), the tutorial says that you should move into the folder named after the `[project_slug]` and setup git from there.  However, this means that only the files contained in that folder will be version controlled. This way, files such as the license, the README, etc. will not be pushed to Github, which I would think need to be there. Moreover, the docs won't be version controlled either.

What is the reasoning behind this? Wouldn't it make sense to version control _all_ files of the project? That is, configuring git at the parent folder of the whole project. Am I missing something?

**Comment by hXtreme** [comment]
I think that you might be confused between `[project_slug]` where the README, LICENSE,... lies and `[project_slug]/[project_slug]` where the code for your package lies.

**Comment by arturomoncadatorres** [comment]
@hXtreme I think you are totally right. Thanks!
