### ISSUE TITLE
Allow choosing license

### ISSUE THREAD

**Issue by breerly** [audreyr/cookiecutter-pypackage#62]
Would be nice to be able to choose MIT, for example.

**Comment by pydanny** [comment]
:+1:

**Comment by eliasdorneles** [comment]
+1, cookiecutter-django can serve as inspiration: https://github.com/pydanny/cookiecutter-django/blob/master/cookiecutter.json#L25

**Comment by stummjr** [comment]
I'm on it.

**Comment by stummjr** [comment]
I'm on it.

**Comment by eliasdorneles** [comment]
Fixed on #135
