### ISSUE TITLE
Allow pytest.

### ISSUE THREAD

**Issue by breerly** [audreyr/cookiecutter-pypackage#63]
Those looking to use pytest with this template have to manually gut unittest ;(

**Comment by pydanny** [comment]
:+1:  We'll add it as an option

**Comment by audreyr** [comment]
I thought more about this. I want to add it but am not sure when I'll get around to it. If anyone wants to submit a pull request for it, that will be fastest.

**Comment by eliasdorneles** [comment]
Added in https://github.com/audreyr/cookiecutter-pypackage/pull/75
