### ISSUE TITLE
tox.ini references non-existent requirements.txt

### ISSUE THREAD

**Issue by kevinastone** [audreyr/cookiecutter-pypackage#70]
https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/tox.ini#L9

**Comment by eliasdorneles** [comment]
Thanks for reportin @kevinastone !
I think we can just remove that, since `python setup.py test` would already install the dependencies declared in `setup.py`.
