### ISSUE TITLE
Error with travis_pypi_setup.py

### ISSUE THREAD

**Issue by thornomad** [audreyr/cookiecutter-pypackage#73]
Hi there - am trying this cookiecutter package out for the first time.  Thanks in advance!

I created initialized my repository, pushed it to github, and created/linked it with travis-ci.  I even pushed another build to get travis-ci to run the tests once (they failed but I wanted to make sure it was linked).  

When I runn `travis_pypi_setup.py` I am getting this error:

    ~$ ./travis_pypi_setup.py
    Traceback (most recent call last):
      File "./travis_pypi_setup.py", line 122, in <module>
        main(args)
      File "./travis_pypi_setup.py", line 107, in main
        public_key = fetch_public_key(args.repo)
      File "./travis_pypi_setup.py", line 61, in fetch_public_key
        data = json.loads(urlopen(keyurl).read())
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'bytes'

Is there something else I need to do?  Do I need my own PGP key ? 

Appreciate it -- am sure I am missing a step.

**Comment by eliasdorneles** [comment]
Hey @thornomad -- thanks for reporting!

It seems I forgot to test properly the script in Python 3, sorry about that!
I'll test it properly and send a PR soon, but I think you can solve the problem by updating the `travis_pypy_setup.py` script, in the function `fetch_public_key`, replace the line:

        data = json.loads(urlopen(keyurl).read())

for:

        data = json.loads(urlopen(keyurl).read().decode('utf-8'))

The reason is that in Python 3, `urlopen(URL).read()` returns bytes(), and we need to decode them into `str` objects before passing it to `json.loads` function.

Please let me know if this helps you or not.
Thanks!

**Comment by thornomad** [comment]
Yes, that fixed it that part ... Thanks.

However, after I enter my PyPI password I receive this error:

    Traceback (most recent call last):
      File "./travis_pypi_setup.py", line 122, in <module>
        main(args)
      File "./travis_pypi_setup.py", line 109, in main
        update_travis_deploy_password(encrypt(public_key, password))
      File "./travis_pypi_setup.py", line 51, in encrypt
        encrypted_password = key.encrypt(password, PKCS1v15())
      File "/Users/thornomad/.virtualenvs/cask-dl/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 583, in encrypt
        return _enc_dec_rsa(self._backend, self, plaintext, padding)
      File "/Users/thornomad/.virtualenvs/cask-dl/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 78, in _enc_dec_rsa
        return _enc_dec_rsa_098(backend, key, data, padding_enum)
      File "/Users/thornomad/.virtualenvs/cask-dl/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 119, in _enc_dec_rsa_098
        res = crypt(len(data), data, buf, key._rsa_cdata, padding_enum)
    TypeError: initializer for ctype 'unsigned char *' must be a bytes or list or tuple, not str

I switched over to a 2.7 virtual environment after that point, however, and used 2.7 and it worked fine.

**Comment by eliasdorneles** [comment]
Hm, yeah -- I'm reinstalling my Linux system now, will have a look at this as soon as possible.
Thank you for reporting!

**Comment by thornomad** [comment]
One other thing - I have had to add the line:

    python: 3.5

To the `.travis..yml` file in order to get the `py35` builds to pass.  I had to do this with another repo as well.  Otherwise you will get an `ERROR: InterpreterNotFound: python3.5` for that set of tox tests.  Thanks!  I think I'm ready to get started...

**Comment by eliasdorneles** [comment]
This was fixed in https://github.com/audreyr/cookiecutter-pypackage/pull/74 and https://github.com/audreyr/cookiecutter-pypackage/commit/2621b10a96b17ee1bfe3e8bb914397ddda26b7d6
