### ISSUE TITLE
remove ReST `:changelog:` directive.

### ISSUE THREAD

**Issue by bionikspoon** [audreyr/cookiecutter-pypackage#80]
What does the `.. :changelog:` directive do?  I could not find it anywhere in the docs for Sphinx or docutils.  It's not in docutils node list, or any reasonable places in Sphinx' source (`sphinx/directives/`, `sphinx/domains/`).  I browsed readthedocs, didn't see it there. 

It seems the only thing it does for certain is break pypi's ability to render rst.

Could I suggest removing it?

**Comment by audreyr** [comment]
This was a workaround that @pydanny added to get the files to render as RST properly on PyPI. Do the relevant sections display on PyPI properly without it?

**Comment by bionikspoon** [comment]
@audreyr That directive was actually being removed from the PyPI description page in the setup.py script.  PyPI uses a very strict rst interpreter that breaks on anything non standard.

I'm glad to see this is safe to remove.  Thanks @audreyr and @pydanny 

ref: #81
