### ISSUE TITLE
Using code-block in Sphinx by default

### ISSUE THREAD

**Issue by miohtama** [audreyr/cookiecutter-pypackage#94]
Does the default installation of Sphinx include Pygments for syntax highlighting (or should this be supported).

This way one could do:

        .. code-block:: console

And 

      .. code-block:: python

In the default usage.rst and installation.rst to get proper syntax highlighting.

**Comment by eliasdorneles** [comment]
Sphinx already assumes Python by default, and so the code in usage.rst is already properly detect and highlighted.

It's true the commands in installation.rst are missing proper highlight, I'll add the console mark -- thanks.
