### ISSUE TITLE
Use pkg_resources to get the package version

### ISSUE THREAD

**Issue by miohtama** [audreyr/cookiecutter-pypackage#96]
In Sphinx conf.py there is reference to `__init__.py` `__version__`.

`__version__` attribute is not preferred or recommended way to get a Python package version. Instead, `pkg_resources` should be used:

    import pkg_resources
    pkg_resources.get_distribution("PIL").version

Please see http://stackoverflow.com/a/17638236/315168 for further discussion.

**Comment by eliasdorneles** [comment]
Hm, I happen to disagree with Martijn Pieters on this one.

The problem with that is that it will always prefer an installed package than the package in current directory (which is what you want to use, when building docs).

Therefore, it assumes a specific development workflow (using a virtualenv + using `python setup.py develop` or `pip install -e .` inside it).
While these are good practices, I'd prefer to leave cookiecutter-pypackage as straightforward as possible for the biggest number of users. Consider, for example, the case of someone trying to build a library that will use system C libraries that are hard to get in a virtualenv.

Apart from being arguably not preferred, do you have some other concern about the current approach?

**Comment by miohtama** [comment]
`__version__` is a practice that predates the current Python package system which is more or less working nowadays. `__version__` discussed detail in here: https://www.python.org/dev/peps/pep-0396/ Package metadata is discussed detail in here: https://www.python.org/dev/peps/pep-0440/ (note that the latter is "accepted" while the former is not, however one wants to interpret this).

Maintaining a version specifier in two separate places creates a maintenance overhead and sets a bad example for new Python users who do not know which scheme is the prevalent one.

I would suggest, with the approval of authors, that both approaches can be taken (if I recall correctly sqlalchemy takes this approach). In `__init__.py`

       import pkg_resources

      __version__ = pkg_resource.get_distribution("myname").

If somebody wants to have non-installed modules they will run a problem with this and are free to hardcode the version information in the module.

**Comment by eliasdorneles** [comment]
We already have bumpversion configured in setup.cfg to deal with release versioning, there is need to set them manually.
There is no maintenance overhead, all you gotta do is use [bumpversion](https://pypi.python.org/pypi/bumpversion).

The hardcoded version number in `__init__.py` is fine, it's more predictable and less prone to import path issues like the dynamic version with pkg_resource is.

Perhaps we should make the instructions for Bumpversion more prominent.

**Comment by yarikoptic** [comment]
Just FY and M (my) information -- got here while searching for more info on `get_distribution` to discover a version of the package. In my case the package is 'citeproc' but the project name is `citeproc-py` so I need to provide `get_distribution("citeproc-py")` not just the `get_distribution("citeproc-py")` and
```
In [26]: citeproc.__name__
Out[26]: 'citeproc'

In [27]: citeproc.__package__
Out[27]: 'citeproc'
```
so not sure how to use `get_distribution` without hardcoding.  There should be some function to return "project name" here but so far couldn't find it.

**Comment by smarie** [comment]
For what's worth, for people who prefer using `setuptools_scm` over `bumpversion`, [here](https://smarie.github.io/python-getversion/#package-versioning-best-practices) is a practice I found useful.
